# Generated by Django 2.1.7 on 2019-04-03 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0003_offer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
